image: node:lts

before_script:
  - npm install

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .vitepress/dist

pages:
  stage: deploy
  script:
    - mv .vitepress/dist public
  artifacts:
    paths:
      - public

  only:
    - main
